version: "3"
services:
  app:
    container_name: covid19
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
        - 3000:3000
    volumes:
        - .:/app
        - node_modules:/app/node_modules
    command: ["sleep", "infinity"]
volumes:
  node_modules: {}
